### ISSUE TITLE
please help to solve this 

### ISSUE THREAD

**Issue by EkanshRajput** [Candida18/Online-Voting-System#1]
![16413123147792489097884738852806](https://user-images.githubusercontent.com/92197239/148087920-e2baa280-b09e-47fc-a442-a2b04c56752e.jpg)
in my pc this is show

**Comment by Candida18** [comment]
First login from the admin side and create a voter profile. Then login using the voter's credentials you just created.

**Comment by EkanshRajput** [comment]
it show error
see image
